export const BATTLE_BACKGROUND_ASSET_KEYS = Object.freeze({
    FOREST:'FOREST'
})

export const MONSTER_ASSET_KEYS = Object.freeze({
    IGUANIGNITE:'IGUANIGNITE',
    CARNODUSK:'CARNODUSK'
})

export const BATTLLE_ASSET_KEYS = Object.freeze({
    HEALTH_BAR_BACKGROUND:'HEALTH_BAR_BACKGROUND'
})

export const HEALTH_BAR_ASSET_KEYS = Object.freeze({
    LEFT_CAP:'LEFT_CAP',
    RIGHT_CAP:'RIGHT_CAP',
    MIDDLE:'MIDDLE',
    LEFT_CAP_SHADOW:'LEFT_CAP_SHADOW',
    RIGHT_CAP_SHADOW:'RIGHT_CAP_SHADOW',
    MIDDLE_SHADOW:'MIDDLE_SHADOW'
})

export const UI_ASSET_KEYS = Object.freeze({
    CURSOR:'CURSOR',
    CURSOR_WHITE:'CURSOR_WHITE',
    MENU_BACKGROUND:'MENU_BACKGROUND',
    MENU_BACKGROUND_GREEN:'MENU_BACKGROUND_GREEN',
    MENU_BACKGROUND_PURPLE:'MENU_BACKGROUND_PURPLE'
})

export const DATA_ASSET_KEYS = Object.freeze({
    ATTACKS:'ATTACKS',
    ANIMATIONS:'ANIMATIONS'
})

export const ATTACK_ASSET_KEYS = Object.freeze({
    ICE_SHARD:'ICE_SHARD',
    ICE_SHARD_START:'ICE_SHARD_START',
    SLASH:'SLASH'
})


export const WORLD_ASSET_KEYS = Object.freeze({
    WORLD_BACKGROUND:'WORLD_BACKGROUND',
    WORLD_MAIN_LEVEL:'WORLD_MAIN_LEVEL',//所有碰撞层json数据
    WORLD_COLLISION:'WORLD_COLLISION',//碰撞层的图片
    WORLD_FOREGROUND:'WORLD_FOREGROUND',//碰撞块上方的图片
    WORLD_ENCOUNTER_ZONE:'WORLD_ENCOUNTER_ZONE'//遭遇怪的碰撞层图片
})

export const CHARACTER_ASSET_KEYS = Object.freeze({
    PLAYER:'PLAYER',
    NPC:'NPC'
})

export const TITLE_ASSET_KEYS = Object.freeze({
    BACKGROUND:'BACKGROUND',
    TITLE:'TITLE',
    PANEL:'PANEL'
})

